1.1 : Importing libraries

In [2]:
import numpy as np
import pandas as pd
import joblib

1.2: Loading models using Joblib

In [ ]:
model = joblib.load("C:\\Users\\HP\\OneDrive\\Desktop\\ML-03_TC-INT-20260601-328\\Smart-Electricity-Consumption\\models\\best_model.pkl")
scaler = joblib.load('C:\\Users\\HP\\OneDrive\\Desktop\\ML-03_TC-INT-20260601-328\\Smart-Electricity-Consumption\\models\\scaler.pkl')
encoder = joblib.load("C:\\Users\\HP\\OneDrive\\Desktop\\ML-03_TC-INT-20260601-328\\Smart-Electricity-Consumption\\models\\encoder.pkl")
print("Models loaded successfully!")

Models loaded successfully!

1.3: Creating sample data

In [4]:
sample_input = {
    "House_Type": "House",
    "Family_Members": 4,
    "Rooms": 5,
    "AC_Hours": 8,
    "Fan_Hours": 10,
    "Refrigerator": 1,
    "Washing_Machine_Hours": 1.2,
    "Water_Motor_Hours": 1.5,
    "Lighting_Hours": 8,
    "Outdoor_Temperature": 35,
    "Season": "Summer",
    "Day_Type": "Weekday",
    "Work_From_Home": "No",
    "Solar_Panels": "No"
}
sample_data = pd.DataFrame([sample_input])
sample_data

,House_Type,Family_Members,Rooms,AC_Hours,Fan_Hours,Refrigerator,Washing_Machine_Hours,Water_Motor_Hours,Lighting_Hours,Outdoor_Temperature,Season,Day_Type,Work_From_Home,Solar_Panels
0,House,4,5,8,10,1,1.2,1.5,8,35,Summer,Weekday,No,No

1.4: Encoding the categorical columns

In [5]:
categorical_columns = [
    "House_Type",
    "Season",
    "Day_Type",
    "Work_From_Home",
    "Solar_Panels"
]

for column in categorical_columns:
    sample_data[column] = encoder[column].transform(sample_data[column])

sample_data

,House_Type,Family_Members,Rooms,AC_Hours,Fan_Hours,Refrigerator,Washing_Machine_Hours,Water_Motor_Hours,Lighting_Hours,Outdoor_Temperature,Season,Day_Type,Work_From_Home,Solar_Panels
0,1,4,5,8,10,1,1.2,1.5,8,35,2,1,0,0

1.5: Scaled the data which is encoded

In [8]:
scaled_data = scaler.transform(sample_data)
scaled_data

array([[ 0.35173309, -0.04787686,  0.48595064,  0.52653173, -0.44973709,
         0.20938323,  0.44494739,  0.57960797, -1.46426033,  1.03191454,
         0.46125023, -0.15090366, -0.62051716, -0.49060655]])

1.6: Predicting from scaled data

In [9]:
prediction = model.predict(scaled_data)

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

1.7: Predicting daily consumption

In [13]:
daily_consumption = round(prediction[0],2)
print(f"Predicted daily consumption : {daily_consumption} KWH")

Predicted daily consumption : 22.18 KWH

1.8: Predicting monthly consumption

In [16]:
monthly_consumption = round(daily_consumption*30 ,2)
print(f"Monthly consumption : {monthly_consumption} Kwh")

Monthly consumption : 665.4 Kwh

1.9: Estimated Monthly Bill

In [22]:
unit_price = 65

monthly_bill = round(monthly_consumption*unit_price , 2)
print(f"Estimared monthly bill will be :{monthly_bill} rs")

Estimared monthly bill will be :43251.0 rs